import { BadRequestException, Injectable } from '@nestjs/common';
import { Diet, MealType, ProteinType, RecipeDifficulty } from '@prisma/client';
import { GeneratedRecipeData, recipeDataSchema } from './ai.types';

@Injectable()
export class AiService {
  async generateRecipeData(prompt: string): Promise<GeneratedRecipeData> {
    const sanitizedPrompt = prompt.trim();

    if (!sanitizedPrompt) {
      throw new BadRequestException(
        'Prompt is required to generate recipe data',
      );
    }

    // @TODO: Placeholder async boundary to mimic future AI integration.
    await Promise.resolve();

    const baseDifficulty = RecipeDifficulty.MEDIUM;
    const rawRecipeData: GeneratedRecipeData = {
      name: 'AI Crafted Dish',
      prompt: sanitizedPrompt,
      description:
        'A balanced and flavorful meal generated by the AI assistant based on your preferences.',
      difficulty: baseDifficulty,
      mealTypes: [MealType.DINNER],
      countriesOfOrigin: ['Global Fusion'],
      diets: [Diet.MEDITERRANEAN],
      allergies: [],
      proteinType: [ProteinType.CHICKEN],
      prepTimeMinutes: 20,
      cookTimeMinutes: 35,
      preparation: [
        'Marinate the protein with spices and herbs for at least 15 minutes.',
        'Prepare the vegetables by washing and slicing them evenly.',
      ],
      instructions: [
        'Heat a large skillet over medium heat and add a drizzle of olive oil.',
        'Sear the marinated protein until golden brown on both sides.',
        'Add the vegetables and cook until tender-crisp.',
        'Deglaze with broth, simmer for 10 minutes, and adjust seasoning to taste.',
      ],
      servingSize: 'Serves 4',
      ingredients: [
        { name: 'Chicken thighs', amount: '500g, boneless and skinless' },
        { name: 'Olive oil', amount: '2 tablespoons' },
        { name: 'Mixed bell peppers', amount: '2 cups, sliced' },
        { name: 'Garlic cloves', amount: '3 cloves, minced' },
        { name: 'Low-sodium chicken broth', amount: '1 cup' },
      ],
      nutritionFacts: {
        calories: 425,
        carbs: 18,
        fat: 22,
        protein: 36,
        fiber: 4,
      },
      miscNutritionFacts: [
        {
          label: 'Sodium',
          value: 620,
          unit: 'mg',
        },
        {
          label: 'Sugar',
          value: 8,
          unit: 'g',
        },
      ],
    };

    return recipeDataSchema.parse(rawRecipeData);
  }

  async generateRecipeImage(prompt: string): Promise<string> {
    const sanitizedPrompt = prompt.trim();

    if (!sanitizedPrompt) {
      throw new BadRequestException(
        'Prompt is required to generate a recipe image',
      );
    }

    // @TODO: Placeholder async boundary to mimic future AI integration.
    await Promise.resolve();

    return `https://images.example.com/recipes/${encodeURIComponent(sanitizedPrompt)}.png`;
  }
}
