import { BadRequestException } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Diet, MealType, ProteinType, RecipeDifficulty } from '@prisma/client';
import type { GeneratedRecipeData } from './ai.types';
import { AiService } from './ai.service';

describe('AiService', () => {
  const createService = async (): Promise<AiService> => {
    const module = await Test.createTestingModule({
      providers: [AiService],
    }).compile();

    return module.get(AiService);
  };

  describe('generateRecipeData', () => {
    it('should produce formatted recipe data that matches the expected schema', async () => {
      const service = await createService();
      const prompt = ' Create a chicken dinner with Mediterranean flavors ';

      const result = await service.generateRecipeData(prompt);

      expect(result).toEqual<GeneratedRecipeData>({
        name: 'AI Crafted Dish',
        prompt: 'Create a chicken dinner with Mediterranean flavors',
        description:
          'A balanced and flavorful meal generated by the AI assistant based on your preferences.',
        difficulty: RecipeDifficulty.MEDIUM,
        mealTypes: [MealType.DINNER],
        countriesOfOrigin: ['Global Fusion'],
        diets: [Diet.MEDITERRANEAN],
        allergies: [],
        proteinType: [ProteinType.CHICKEN],
        prepTimeMinutes: 20,
        cookTimeMinutes: 35,
        preparation: [
          'Marinate the protein with spices and herbs for at least 15 minutes.',
          'Prepare the vegetables by washing and slicing them evenly.',
        ],
        instructions: [
          'Heat a large skillet over medium heat and add a drizzle of olive oil.',
          'Sear the marinated protein until golden brown on both sides.',
          'Add the vegetables and cook until tender-crisp.',
          'Deglaze with broth, simmer for 10 minutes, and adjust seasoning to taste.',
        ],
        servingSize: 'Serves 4',
        ingredients: [
          { name: 'Chicken thighs', amount: '500g, boneless and skinless' },
          { name: 'Olive oil', amount: '2 tablespoons' },
          { name: 'Mixed bell peppers', amount: '2 cups, sliced' },
          { name: 'Garlic cloves', amount: '3 cloves, minced' },
          { name: 'Low-sodium chicken broth', amount: '1 cup' },
        ],
        nutritionFacts: {
          calories: 425,
          carbs: 18,
          fat: 22,
          protein: 36,
          fiber: 4,
        },
        miscNutritionFacts: [
          {
            label: 'Sodium',
            value: 620,
            unit: 'mg',
          },
          {
            label: 'Sugar',
            value: 8,
            unit: 'g',
          },
        ],
      });
    });

    it('should throw a BadRequestException when prompt is empty', async () => {
      const service = await createService();

      await expect(service.generateRecipeData('   ')).rejects.toThrow(
        BadRequestException,
      );
    });
  });

  describe('generateRecipeImage', () => {
    it('should generate an image url using the prompt', async () => {
      const service = await createService();
      const prompt = 'Creamy risotto with mushrooms';

      const result = await service.generateRecipeImage(prompt);

      expect(result).toBe(
        'https://images.example.com/recipes/Creamy%20risotto%20with%20mushrooms.png',
      );
    });

    it('should throw a BadRequestException when prompt is missing', async () => {
      const service = await createService();

      await expect(service.generateRecipeImage('')).rejects.toThrow(
        BadRequestException,
      );
    });
  });
});
