import {
  BadRequestException,
  InternalServerErrorException,
} from '@nestjs/common';
import { Test } from '@nestjs/testing';
import {
  Diet,
  MealType,
  ProteinType,
  RecipeDifficulty,
  type RecipeImage,
} from '@prisma/client';
import { PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import OpenAI from 'openai';
import { AiService } from './ai.service';
import type { RecipeData } from './ai.types';
import { recipeResponseFormat, recipeValidFormat } from './ai.types';
import { PrismaService } from '../prisma/prisma.service';
import * as crypto from 'node:crypto';

describe('AiService', () => {
  let parseMock: jest.Mock | undefined = undefined;
  let imageMock: jest.Mock | undefined = undefined;
  let moderationMock: jest.Mock | undefined = undefined;
  let s3SendMock: jest.Mock<Promise<void>, [PutObjectCommand]> | undefined =
    undefined;
  let prismaCreateMock: jest.Mock<Promise<RecipeImage>, [unknown]> | undefined =
    undefined;

  const originalEnv = process.env;

  const createService = async (options?: {
    openAiClient?: Partial<OpenAI> | null;
  }): Promise<AiService> => {
    parseMock = jest.fn();
    imageMock = jest.fn();
    moderationMock = jest.fn();
    s3SendMock = jest.fn<Promise<void>, [PutObjectCommand]>();
    prismaCreateMock = jest.fn<Promise<RecipeImage>, [unknown]>();

    const defaultOpenAiClient = {
      responses: {
        parse: parseMock,
      },
      images: {
        generate: imageMock,
      },
      moderations: {
        create: moderationMock,
      },
    };

    const providedClient =
      options?.openAiClient === null
        ? undefined
        : (options?.openAiClient ?? defaultOpenAiClient);

    const module = await Test.createTestingModule({
      providers: [
        AiService,
        {
          provide: OpenAI,
          useValue: providedClient,
        },
        {
          provide: PrismaService,
          useValue: {
            recipeImage: {
              create: prismaCreateMock,
            },
          },
        },
        {
          provide: S3Client,
          useValue: {
            send: s3SendMock,
          },
        },
      ],
    }).compile();

    return module.get(AiService);
  };

  const recipeData: RecipeData = {
    name: 'AI Crafted Dish',
    prompt: 'Create a chicken dinner with Mediterranean flavors',
    description:
      'A balanced and flavorful meal generated by the AI assistant based on your preferences.',
    difficulty: RecipeDifficulty.MEDIUM,
    mealTypes: [MealType.DINNER],
    countriesOfOrigin: ['Global Fusion'],
    diets: [Diet.MEDITERRANEAN],
    allergies: [],
    proteinType: [ProteinType.CHICKEN],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    preparation: [
      'Marinate the protein with spices and herbs for at least 15 minutes.',
      'Prepare the vegetables by washing and slicing them evenly.',
    ],
    instructions: [
      'Heat a large skillet over medium heat and add a drizzle of olive oil.',
      'Sear the marinated protein until golden brown on both sides.',
      'Add the vegetables and cook until tender-crisp.',
      'Deglaze with broth, simmer for 10 minutes, and adjust seasoning to taste.',
    ],
    servingSize: 'Serves 4',
    ingredients: [
      { name: 'Chicken thighs', amount: '500g, boneless and skinless' },
      { name: 'Olive oil', amount: '2 tablespoons' },
      { name: 'Mixed bell peppers', amount: '2 cups, sliced' },
      { name: 'Garlic cloves', amount: '3 cloves, minced' },
      { name: 'Low-sodium chicken broth', amount: '1 cup' },
    ],
    nutritionFacts: {
      calories: 425,
      carbs: 18,
      fat: 22,
      protein: 36,
      fiber: 4,
    },
    miscNutritionFacts: [
      {
        label: 'Sodium',
        value: 620,
        unit: 'mg',
      },
      {
        label: 'Sugar',
        value: 8,
        unit: 'g',
      },
    ],
  };

  let service: AiService | undefined = undefined;
  const recipeId = 'recipe-id-123';

  beforeEach(async () => {
    process.env = { ...originalEnv };
    process.env.SPACES_ENDPOINT = 'http://localhost:9000';
    process.env.SPACES_REGION = 'us-east-1';
    process.env.SPACES_ACCESS_KEY_ID = 'local-test-access-key';
    process.env.SPACES_SECRET_ACCESS_KEY = 'local-test-secret-key';
    process.env.SPACES_BUCKET = 'tasteloop-dev';
    process.env.SPACES_FORCE_PATH_STYLE = 'true';
    process.env.SPACES_OBJECT_ACL = 'public-read';
    service = await createService();
  });

  afterEach(() => {
    jest.restoreAllMocks();
    jest.clearAllMocks();
    process.env = originalEnv;
  });

  describe('generateRecipeData', () => {
    it('should return the recipe data parsed by OpenAI', async () => {
      const prompt = ' Create a chicken dinner with Mediterranean flavors ';
      const sanitizedPrompt = prompt.trim();

      // Mock moderation
      moderationMock?.mockResolvedValue({
        results: [{ flagged: false }],
      });

      // Mock recipe validation
      parseMock?.mockResolvedValueOnce({
        output_parsed: { isRecipeRelated: true },
      });

      // Mock recipe generation
      parseMock?.mockResolvedValueOnce({
        output_parsed: recipeData,
      });

      const result = await service?.generateRecipeData(prompt);

      // Check moderation was called with sanitized prompt
      expect(moderationMock).toHaveBeenCalledWith({
        model: 'omni-moderation-latest',
        input: sanitizedPrompt,
      });

      // Check validation was called with sanitized prompt
      expect(parseMock).toHaveBeenNthCalledWith(1, {
        model: 'gpt-5-nano',
        input: sanitizedPrompt,
        instructions:
          'Determine if the user prompt is related to food and cooking recipes. The prompt will be used to generate a cooking recipe if it is relevant.',
        text: { format: recipeValidFormat },
      });

      // Check recipe generation was called with sanitized prompt
      expect(parseMock).toHaveBeenNthCalledWith(2, {
        model: 'gpt-5-mini',
        input: sanitizedPrompt,
        instructions:
          'You are a helpful assistant that provides detailed cooking recipes based on user prompts. All the instructions and details should be should be clear, concise, and easy to follow.',
        text: { format: recipeResponseFormat },
      });

      expect(result).toEqual(recipeData);
    });

    it('should throw a BadRequestException when moderation flags content', async () => {
      const prompt = 'Inappropriate content';

      moderationMock?.mockResolvedValue({
        results: [{ flagged: true }],
      });

      await expect(service?.generateRecipeData(prompt)).rejects.toThrow(
        new BadRequestException(
          'The provided prompt violates content policies.',
        ),
      );

      expect(moderationMock).toHaveBeenCalledWith({
        model: 'omni-moderation-latest',
        input: prompt,
      });
      expect(parseMock).not.toHaveBeenCalled();
    });

    it('should throw a BadRequestException when prompt is not recipe-related', async () => {
      const prompt = 'Tell me about quantum physics';

      moderationMock?.mockResolvedValue({
        results: [{ flagged: false }],
      });

      parseMock?.mockResolvedValueOnce({
        output_parsed: { isRecipeRelated: false },
      });

      await expect(service?.generateRecipeData(prompt)).rejects.toThrow(
        new BadRequestException(
          'The provided prompt does not seem to be related to recipes.',
        ),
      );

      expect(moderationMock).toHaveBeenCalled();
      expect(parseMock).toHaveBeenCalledTimes(1);
    });

    it('should throw a BadRequestException when prompt is empty', async () => {
      await expect(service?.generateRecipeData('   ')).rejects.toThrow(
        BadRequestException,
      );
      expect(moderationMock).not.toHaveBeenCalled();
      expect(parseMock).not.toHaveBeenCalled();
    });

    it('should throw when OpenAI does not return recipe data', async () => {
      moderationMock?.mockResolvedValue({
        results: [{ flagged: false }],
      });

      parseMock?.mockResolvedValueOnce({
        output_parsed: { isRecipeRelated: true },
      });

      parseMock?.mockResolvedValueOnce({
        output_parsed: null,
      });

      await expect(service?.generateRecipeData('Valid prompt')).rejects.toThrow(
        InternalServerErrorException,
      );
    });

    it('should surface OpenAI errors as InternalServerErrorException', async () => {
      moderationMock?.mockResolvedValue({
        results: [{ flagged: false }],
      });

      parseMock?.mockResolvedValueOnce({
        output_parsed: { isRecipeRelated: true },
      });

      parseMock?.mockRejectedValueOnce(new Error('OpenAI failure'));

      await expect(service?.generateRecipeData('Valid prompt')).rejects.toThrow(
        InternalServerErrorException,
      );
    });

    it('should throw an InternalServerErrorException when OpenAI client is missing', async () => {
      const serviceWithoutClient = await createService({
        openAiClient: null,
      });

      await expect(
        serviceWithoutClient.generateRecipeData('Valid prompt'),
      ).rejects.toThrow(InternalServerErrorException);
    });
  });

  describe('generateRecipeImage', () => {
    it('should store image data and persist metadata', async () => {
      if (service == null) {
        throw new Error('AiService was not initialized');
      }
      if (prismaCreateMock == null || s3SendMock == null) {
        throw new Error('Mocks were not initialized');
      }

      const expectedPrompt = [
        `A high-quality, cinematic food photograph of "${recipeData.name}"`,
        recipeData.description,
        `Key ingredients: ${recipeData.ingredients
          .map((ingredient) => `${ingredient.name} (${ingredient.amount})`)
          .join(', ')}.`,
        'Style: natural light, shallow depth of field, vibrant colors, soft shadows, no text, no labels, no people, professional food styling.',
      ].join('\n');

      const uuidSpy = jest
        .spyOn(crypto, 'randomUUID')
        .mockReturnValue('image-uuid');

      const bucket = process.env.SPACES_BUCKET;
      const region = process.env.SPACES_REGION;

      if (bucket == null || region == null) {
        throw new Error('Storage environment variables are not configured');
      }

      const createdImage: RecipeImage = {
        id: 'recipe-image-id',
        recipeId,
        spaceName: bucket,
        region,
        objectKey: `recipes/${recipeId}/ai-crafted-dish-image-uuid.png`,
        fileName: 'ai-crafted-dish-image-uuid.png',
        contentType: 'image/png',
        createdAt: new Date('2024-01-01T00:00:00.000Z'),
        updatedAt: new Date('2024-01-01T00:00:00.000Z'),
      };

      imageMock?.mockResolvedValue({
        data: [
          {
            b64_json: Buffer.from('fake-image-data').toString('base64'),
          },
        ],
      });

      prismaCreateMock.mockImplementation(async (args) => {
        expect(args).toEqual({
          data: {
            recipe: {
              connect: {
                id: recipeId,
              },
            },
            spaceName: bucket,
            region,
            objectKey: `recipes/${recipeId}/ai-crafted-dish-image-uuid.png`,
            fileName: 'ai-crafted-dish-image-uuid.png',
            contentType: 'image/png',
          },
        });

        return Promise.resolve(createdImage);
      });

      const result = await service.generateRecipeImage(recipeId, recipeData);

      expect(imageMock).toHaveBeenCalledWith({
        model: 'gpt-image-1',
        size: '1024x1024',
        prompt: expectedPrompt,
        response_format: 'b64_json',
      });

      expect(s3SendMock).toHaveBeenCalledTimes(1);
      const [[putObjectCommand]] = s3SendMock.mock.calls;
      expect(putObjectCommand).toBeInstanceOf(PutObjectCommand);
      if (!(putObjectCommand instanceof PutObjectCommand)) {
        throw new Error('Unexpected S3 command issued');
      }

      expect(putObjectCommand.input).toMatchObject({
        Bucket: bucket,
        Key: `recipes/${recipeId}/ai-crafted-dish-image-uuid.png`,
        ContentType: 'image/png',
        ACL: 'public-read',
      });

      expect(prismaCreateMock).toHaveBeenCalledTimes(1);
      expect(result).toEqual(createdImage);

      uuidSpy.mockRestore();
    });

    it('should throw an error when OpenAI does not return image data', async () => {
      if (service == null) {
        throw new Error('AiService was not initialized');
      }

      imageMock?.mockResolvedValue({
        data: [{}],
      });

      await expect(
        service.generateRecipeImage(recipeId, recipeData),
      ).rejects.toThrow(InternalServerErrorException);

      expect(s3SendMock).not.toHaveBeenCalled();
      expect(prismaCreateMock).not.toHaveBeenCalled();
    });

    it('should surface OpenAI errors when generating an image', async () => {
      if (service == null) {
        throw new Error('AiService was not initialized');
      }

      imageMock?.mockRejectedValue(new Error('OpenAI failure'));

      await expect(
        service.generateRecipeImage(recipeId, recipeData),
      ).rejects.toThrow(InternalServerErrorException);

      expect(s3SendMock).not.toHaveBeenCalled();
      expect(prismaCreateMock).not.toHaveBeenCalled();
    });

    it('should throw an InternalServerErrorException when OpenAI client is missing', async () => {
      const serviceWithoutClient = await createService({
        openAiClient: null,
      });

      await expect(
        serviceWithoutClient.generateRecipeImage(recipeId, recipeData),
      ).rejects.toThrow(InternalServerErrorException);
    });
  });
});
