import {
  BadRequestException,
  InternalServerErrorException,
} from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { Diet, MealType, ProteinType, RecipeDifficulty } from '@prisma/client';
import OpenAI from 'openai';
import { AiService } from './ai.service';
import type { RecipeData } from './ai.types';
import { recipeResponseFormat } from './ai.types';

describe('AiService', () => {
  let parseMock: jest.Mock | undefined = undefined;
  let imageMock: jest.Mock | undefined = undefined;

  const createService = async (options?: {
    openAiClient?: Partial<OpenAI> | null;
  }): Promise<AiService> => {
    parseMock = jest.fn();
    imageMock = jest.fn();

    const defaultOpenAiClient = {
      responses: {
        parse: parseMock,
      },
      images: {
        generate: imageMock,
      },
    };

    const providedClient =
      options?.openAiClient === null
        ? undefined
        : (options?.openAiClient ?? defaultOpenAiClient);

    const module = await Test.createTestingModule({
      providers: [
        AiService,
        {
          provide: OpenAI,
          useValue: providedClient,
        },
      ],
    }).compile();

    return module.get(AiService);
  };

  const recipeData: RecipeData = {
    name: 'AI Crafted Dish',
    prompt: 'Create a chicken dinner with Mediterranean flavors',
    description:
      'A balanced and flavorful meal generated by the AI assistant based on your preferences.',
    difficulty: RecipeDifficulty.MEDIUM,
    mealTypes: [MealType.DINNER],
    countriesOfOrigin: ['Global Fusion'],
    diets: [Diet.MEDITERRANEAN],
    allergies: [],
    proteinType: [ProteinType.CHICKEN],
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    preparation: [
      'Marinate the protein with spices and herbs for at least 15 minutes.',
      'Prepare the vegetables by washing and slicing them evenly.',
    ],
    instructions: [
      'Heat a large skillet over medium heat and add a drizzle of olive oil.',
      'Sear the marinated protein until golden brown on both sides.',
      'Add the vegetables and cook until tender-crisp.',
      'Deglaze with broth, simmer for 10 minutes, and adjust seasoning to taste.',
    ],
    servingSize: 'Serves 4',
    ingredients: [
      { name: 'Chicken thighs', amount: '500g, boneless and skinless' },
      { name: 'Olive oil', amount: '2 tablespoons' },
      { name: 'Mixed bell peppers', amount: '2 cups, sliced' },
      { name: 'Garlic cloves', amount: '3 cloves, minced' },
      { name: 'Low-sodium chicken broth', amount: '1 cup' },
    ],
    nutritionFacts: {
      calories: 425,
      carbs: 18,
      fat: 22,
      protein: 36,
      fiber: 4,
    },
    miscNutritionFacts: [
      {
        label: 'Sodium',
        value: 620,
        unit: 'mg',
      },
      {
        label: 'Sugar',
        value: 8,
        unit: 'g',
      },
    ],
  };

  let service: AiService | undefined = undefined;

  beforeEach(async () => {
    service = await createService();
  });

  describe('generateRecipeData', () => {
    it('should return the recipe data parsed by OpenAI', async () => {
      const prompt = ' Create a chicken dinner with Mediterranean flavors ';
      parseMock?.mockResolvedValue({
        output_parsed: recipeData,
      });

      const result = await service?.generateRecipeData(prompt);

      expect(parseMock).toHaveBeenCalledWith({
        model: 'gpt-5',
        input: prompt,
        instructions:
          'You are a helpful assistant that provides detailed cooking recipes based on user prompts. All the instructions and details should be should be clear, concise, and easy to follow.',
        text: { format: recipeResponseFormat },
      });
      expect(result).toEqual(recipeData);
    });

    it('should throw a BadRequestException when prompt is empty', async () => {
      await expect(service?.generateRecipeData('   ')).rejects.toThrow(
        BadRequestException,
      );
      expect(parseMock).not.toHaveBeenCalled();
    });

    it('should throw when OpenAI does not return recipe data', async () => {
      parseMock?.mockResolvedValue({
        output_parsed: null,
      });

      await expect(service?.generateRecipeData('Valid prompt')).rejects.toThrow(
        InternalServerErrorException,
      );
    });

    it('should surface OpenAI errors as InternalServerErrorException', async () => {
      parseMock?.mockRejectedValue(new Error('OpenAI failure'));

      await expect(service?.generateRecipeData('Valid prompt')).rejects.toThrow(
        InternalServerErrorException,
      );
    });

    it('should throw an InternalServerErrorException when OpenAI client is missing', async () => {
      const serviceWithoutClient = await createService({
        openAiClient: null,
      });

      await expect(
        serviceWithoutClient.generateRecipeData('Valid prompt'),
      ).rejects.toThrow(InternalServerErrorException);
    });
  });

  describe('generateRecipeImage', () => {
    it('should generate an image url using the recipe data', async () => {
      const expectedPrompt = [
        `A high-quality, cinematic food photograph of "${recipeData.name}"`,
        recipeData.description,
        `Key ingredients: ${recipeData.ingredients
          .map((ingredient) => `${ingredient.name} (${ingredient.amount})`)
          .join(', ')}.`,
        'Style: natural light, shallow depth of field, vibrant colors, soft shadows, no text, no labels, no people, professional food styling.',
      ].join('\n');

      imageMock?.mockResolvedValue({
        data: [
          {
            url: 'https://images.example.com/recipes/Creamy%20risotto%20with%20mushrooms.png',
          },
        ],
      });

      const result = await service?.generateRecipeImage(recipeData);

      expect(imageMock).toHaveBeenCalledWith({
        model: 'gpt-image-1',
        size: '1024x1024',
        prompt: expectedPrompt,
      });
      expect(result).toBe(
        'https://images.example.com/recipes/Creamy%20risotto%20with%20mushrooms.png',
      );
    });

    it('should throw an error when OpenAI does not return a URL', async () => {
      imageMock?.mockResolvedValue({
        data: [{}],
      });

      await expect(service?.generateRecipeImage(recipeData)).rejects.toThrow(
        InternalServerErrorException,
      );
    });

    it('should surface OpenAI errors when generating an image', async () => {
      imageMock?.mockRejectedValue(new Error('OpenAI failure'));

      await expect(service?.generateRecipeImage(recipeData)).rejects.toThrow(
        InternalServerErrorException,
      );
    });

    it('should throw an InternalServerErrorException when OpenAI client is missing', async () => {
      const serviceWithoutClient = await createService({
        openAiClient: null,
      });

      await expect(
        serviceWithoutClient.generateRecipeImage(recipeData),
      ).rejects.toThrow(InternalServerErrorException);
    });
  });
});
